In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("IMDB_Dataset.csv")
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [3]:
df.shape

(50000, 2)

In [4]:
print(df['sentiment'].value_counts())

sentiment
positive    25000
negative    25000
Name: count, dtype: int64

In [4]:
df['sentiment'] = df['sentiment'].map({
    'positive': 1,
    'negative': 0
})

In [5]:
df.head()

                                              review  sentiment
0  One of the other reviewers has mentioned that ...          1
1  A wonderful little production. <br /><br />The...          1
2  I thought this was a wonderful way to spend ti...          1
3  Basically there's a family where a little boy ...          0
4  Petter Mattei's "Love in the Time of Money" is...          1

In [6]:
X = df['review'].values
y = df['sentiment'].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [7]:
y_train, y_test

(array([0, 0, 1, ..., 0, 1, 1], dtype=int64),
 array([1, 1, 0, ..., 1, 0, 1], dtype=int64))

In [8]:
VOCAB_SIZE = 10000
MAX_LEN = 200          #length of a review is 200 max

tokenizer = Tokenizer(num_words=VOCAB_SIZE, oov_token="<OOV>")    #OOV out of vocablary tokens will be replaced with <OOV>
tokenizer.fit_on_texts(X_train)     #converts vored in to tokes

In [9]:
tokenizer.word_index

{'<OOV>': 1,
 'the': 2,
 'and': 3,
 'a': 4,
 'of': 5,
 'to': 6,
 'is': 7,
 'br': 8,
 'in': 9,
 'it': 10,
 'i': 11,
 'this': 12,
 'that': 13,
 'was': 14,
 'as': 15,
 'for': 16,
 'with': 17,
 'movie': 18,
 'but': 19,
 'film': 20,
 'on': 21,
 'not': 22,
 'you': 23,
 'are': 24,
 'his': 25,
 'have': 26,
 'be': 27,
 'one': 28,
 'he': 29,
 'all': 30,
 'at': 31,
 'by': 32,
 'an': 33,
 'they': 34,
 'so': 35,
 'from': 36,
 'who': 37,
 'like': 38,
 'or': 39,
 'just': 40,
 'her': 41,
 'out': 42,
 'about': 43,
 'if': 44,
 "it's": 45,
 'has': 46,
 'there': 47,
 'some': 48,
 'what': 49,
 'good': 50,
 'more': 51,
 'very': 52,
 'when': 53,
 'up': 54,
 'no': 55,
 'time': 56,
 'my': 57,
 'even': 58,
 'she': 59,
 'would': 60,
 'which': 61,
 'only': 62,
 'story': 63,
 'really': 64,
 'see': 65,
 'their': 66,
 'had': 67,
 'can': 68,
 'me': 69,
 'well': 70,
 'were': 71,
 'we': 72,
 'than': 73,
 'much': 74,
 'bad': 75,
 'been': 76,
 'do': 77,
 'get': 78,
 'great': 79,
 'also': 80,
 'will': 81,
 'other': 82,
 'into': 83,
 'people': 84,
 'because': 85,
 'first': 86,
 'how': 87,
 'him': 88,
 'most': 89,
 "don't": 90,
 'made': 91,
 'then': 92,
 'them': 93,
 'make': 94,
 'its': 95,
 'way': 96,
 'movies': 97,
 'could': 98,
 'too': 99,
 'any': 100,
 'after': 101,
 'think': 102,
 'characters': 103,
 'watch': 104,
 'films': 105,
 'seen': 106,
 'two': 107,
 'many': 108,
 'character': 109,
 'being': 110,
 'plot': 111,
 'never': 112,
 'acting': 113,
 'love': 114,
 'life': 115,
 'best': 116,
 'did': 117,
 'where': 118,
 'know': 119,
 'little': 120,
 'show': 121,
 'over': 122,
 'ever': 123,
 'off': 124,
 'does': 125,
 'your': 126,
 'better': 127,
 'end': 128,
 'scene': 129,
 'man': 130,
 'still': 131,
 'say': 132,
 'these': 133,
 'here': 134,
 'scenes': 135,
 'why': 136,
 'while': 137,
 'something': 138,
 'such': 139,
 'go': 140,
 'through': 141,
 'back': 142,
 'should': 143,
 'real': 144,
 "i'm": 145,
 'those': 146,
 'watching': 147,
 'now': 148,
 'thing': 149,
 "doesn't": 150,
 'though': 151,
 'actors': 152,
 'years': 153,
 "didn't": 154,
 'funny': 155,
 '10': 156,
 'old': 157,
 'another': 158,
 'actually': 159,
 'before': 160,
 'work': 161,
 'makes': 162,
 'nothing': 163,
 'look': 164,
 'going': 165,
 'find': 166,
 'director': 167,
 'same': 168,
 'lot': 169,
 'new': 170,
 'again': 171,
 'few': 172,
 'every': 173,
 'part': 174,
 'cast': 175,
 'us': 176,
 'things': 177,
 'down': 178,
 'quite': 179,
 'world': 180,
 'want': 181,
 'pretty': 182,
 'horror': 183,
 'around': 184,
 'seems': 185,
 'take': 186,
 'got': 187,
 'thought': 188,
 'however': 189,
 'young': 190,
 'long': 191,
 'fact': 192,
 'enough': 193,
 'big': 194,
 "can't": 195,
 'both': 196,
 'give': 197,
 "that's": 198,
 "i've": 199,
 'may': 200,
 'own': 201,
 'series': 202,
 'action': 203,
 'right': 204,
 'without': 205,
 'must': 206,
 'between': 207,
 'music': 208,
 'comedy': 209,
 'original': 210,
 'times': 211,
 'always': 212,
 'saw': 213,
 'come': 214,
 'almost': 215,
 "isn't": 216,
 'role': 217,
 'gets': 218,
 'point': 219,
 'least': 220,
 'whole': 221,
 'done': 222,
 'interesting': 223,
 "there's": 224,
 'guy': 225,
 'far': 226,
 'script': 227,
 'minutes': 228,
 'bit': 229,
 'feel': 230,
 '2': 231,
 'making': 232,
 'anything': 233,
 'since': 234,
 'family': 235,
 'am': 236,
 'might': 237,
 'probably': 238,
 'last': 239,
 'tv': 240,
 "he's": 241,
 'performance': 242,
 'away': 243,
 'kind': 244,
 'worst': 245,
 'yet': 246,
 'fun': 247,
 'hard': 248,
 'sure': 249,
 'anyone': 250,
 'girl': 251,
 'rather': 252,
 'found': 253,
 'each': 254,
 'played': 255,
 'day': 256,
 'although': 257,
 'looking': 258,
 'woman': 259,
 'our': 260,
 'believe': 261,
 'screen': 262,
 'having': 263,
 'especially': 264,
 'trying': 265,
 'course': 266,
 'dvd': 267,
 'everything': 268,
 'set': 269,
 'ending': 270,
 'put': 271,
 'goes': 272,
 'maybe': 273,
 'comes': 274,
 'shows': 275,
 'place': 276,
 'worth': 277,
 'book': 278,
 'different': 279,
 'main': 280,
 'three': 281,
 'effects': 282,
 'once': 283,
 'sense': 284,
 'watched': 285,
 'looks': 286,
 'reason': 287,
 'money': 288,
 'actor': 289,
 'american': 290,
 'true': 291,
 "wasn't": 292,
 'together': 293,
 'play': 294,
 'job': 295,
 'someone': 296,
 'war': 297,
 'high': 298,
 'special': 299,
 'instead': 300,
 'year': 301,
 'everyone': 302,
 'during': 303,
 '1': 304,
 'later': 305,
 'half': 306,
 'takes': 307,
 'said': 308,
 'plays': 309,
 'left': 310,
 'audience': 311,
 'himself': 312,
 'seem': 313,
 'night': 314,
 'seeing': 315,
 'beautiful': 316,
 'excellent': 317,
 'shot': 318,
 'john': 319,
 'house': 320,
 'black': 321,
 'version': 322,
 'idea': 323,
 'fan': 324,
 'mind': 325,
 'death': 326,
 'wife': 327,
 'star': 328,
 'budget': 329,
 'short': 330,
 'used': 331,
 'nice': 332,
 'second': 333,
 'poor': 334,
 'simply': 335,
 '3': 336,
 'else': 337,
 'completely': 338,
 "you're": 339,
 'read': 340,
 'top': 341,
 'along': 342,
 'either': 343,
 'home': 344,
 'boring': 345,
 'less': 346,
 'men': 347,
 'help': 348,
 'dead': 349,
 'line': 350,
 'friends': 351,
 'try': 352,
 'production': 353,
 'father': 354,
 'enjoy': 355,
 'kids': 356,
 'given': 357,
 'camera': 358,
 'until': 359,
 'need': 360,
 'wrong': 361,
 'low': 362,
 'use': 363,
 'classic': 364,
 'full': 365,
 'performances': 366,
 'rest': 367,
 'next': 368,
 'stupid': 369,
 'truly': 370,
 'school': 371,
 'couple': 372,
 'hollywood': 373,
 'video': 374,
 'recommend': 375,
 'tell': 376,
 'awful': 377,
 'start': 378,
 'sex': 379,
 'let': 380,
 'mean': 381,
 'terrible': 382,
 'women': 383,
 'came': 384,
 'name': 385,
 'perhaps': 386,
 'understand': 387,
 'moments': 388,
 'wonderful': 389,
 'remember': 390,
 'getting': 391,
 'episode': 392,
 'itself': 393,
 'human': 394,
 'keep': 395,
 'face': 396,
 'style': 397,
 'small': 398,
 'early': 399,
 'stars': 400,
 'written': 401,
 'person': 402,
 'head': 403,
 'definitely': 404,
 'playing': 405,
 'others': 406,
 'perfect': 407,
 'doing': 408,
 'often': 409,
 'gives': 410,
 'dialogue': 411,
 'lines': 412,
 'mother': 413,
 'case': 414,
 'finally': 415,
 "couldn't": 416,
 'piece': 417,
 'title': 418,
 'boy': 419,
 'went': 420,
 'certainly': 421,
 'live': 422,
 'oh': 423,
 'liked': 424,
 'absolutely': 425,
 'laugh': 426,
 'sort': 427,
 'loved': 428,
 'hope': 429,
 'worse': 430,
 'entertaining': 431,
 'yes': 432,
 'lost': 433,
 'become': 434,
 'several': 435,
 '5': 436,
 'based': 437,
 'sound': 438,
 'entire': 439,
 'friend': 440,
 'called': 441,
 'supposed': 442,
 'overall': 443,
 'picture': 444,
 'felt': 445,
 'problem': 446,
 'mr': 447,
 'cinema': 448,
 'guys': 449,
 'waste': 450,
 '4': 451,
 'totally': 452,
 'drama': 453,
 'beginning': 454,
 'care': 455,
 'direction': 456,
 'against': 457,
 'white': 458,
 'dark': 459,
 'under': 460,
 'wanted': 461,
 'seemed': 462,
 'game': 463,
 'humor': 464,
 'fans': 465,
 'turn': 466,
 "you'll": 467,
 'lives': 468,
 'children': 469,
 "she's": 470,
 'lead': 471,
 'already': 472,
 'despite': 473,
 'evil': 474,
 'example': 475,
 'throughout': 476,
 'final': 477,
 'becomes': 478,
 'quality': 479,
 'guess': 480,
 'unfortunately': 481,
 'days': 482,
 'able': 483,
 'history': 484,
 'fine': 485,
 "i'd": 486,
 'writing': 487,
 'heart': 488,
 'side': 489,
 'wants': 490,
 'flick': 491,
 'horrible': 492,
 'b': 493,
 'killer': 494,
 'son': 495,
 'matter': 496,
 'run': 497,
 'kill': 498,
 '\x96': 499,
 'amazing': 500,
 'michael': 501,
 'enjoyed': 502,
 'close': 503,
 'art': 504,
 'etc': 505,
 'works': 506,
 'act': 507,
 'behind': 508,
 'tries': 509,
 'past': 510,
 'gave': 511,
 'brilliant': 512,
 "they're": 513,
 'eyes': 514,
 "won't": 515,
 'directed': 516,
 'genre': 517,
 'expect': 518,
 'turns': 519,
 'town': 520,
 'themselves': 521,
 'hand': 522,
 'favorite': 523,
 'car': 524,
 'parts': 525,
 'late': 526,
 'killed': 527,
 'hour': 528,
 'soon': 529,
 'stuff': 530,
 'girls': 531,
 'viewer': 532,
 'actress': 533,
 'obviously': 534,
 'myself': 535,
 'decent': 536,
 'says': 537,
 'highly': 538,
 'thinking': 539,
 'city': 540,
 'group': 541,
 'child': 542,
 'starts': 543,
 'stop': 544,
 'sometimes': 545,
 'heard': 546,
 'anyway': 547,
 'kid': 548,
 'type': 549,
 'self': 550,
 'god': 551,
 'known': 552,
 'happens': 553,
 'except': 554,
 'took': 555,
 'voice': 556,
 'blood': 557,
 'fight': 558,
 'daughter': 559,
 'told': 560,
 'feeling': 561,
 'slow': 562,
 'experience': 563,
 'leave': 564,
 'coming': 565,
 'score': 566,
 'strong': 567,
 'writer': 568,
 'including': 569,
 'stories': 570,
 'violence': 571,
 'happen': 572,
 'extremely': 573,
 'ok': 574,
 'involved': 575,
 'lack': 576,
 'cannot': 577,
 'police': 578,
 'moment': 579,
 'wonder': 580,
 's': 581,
 'age': 582,
 'obvious': 583,
 'crap': 584,
 'living': 585,
 'save': 586,
 'particularly': 587,
 'looked': 588,
 "wouldn't": 589,
 'chance': 590,
 'please': 591,
 'shown': 592,
 'cut': 593,
 'complete': 594,
 'song': 595,
 'attempt': 596,
 'ago': 597,
 'hell': 598,
 'murder': 599,
 'cool': 600,
 'happened': 601,
 'roles': 602,
 'simple': 603,
 'gore': 604,
 'hit': 605,
 'hilarious': 606,
 'taken': 607,
 'english': 608,
 'released': 609,
 'serious': 610,
 'interest': 611,
 'james': 612,
 'opening': 613,
 'hours': 614,
 'robert': 615,
 'brother': 616,
 'david': 617,
 'possible': 618,
 'jokes': 619,
 'number': 620,
 'seriously': 621,
 'across': 622,
 'usually': 623,
 'talent': 624,
 'none': 625,
 'cinematography': 626,
 'yourself': 627,
 'today': 628,
 'order': 629,
 'view': 630,
 'hero': 631,
 'saying': 632,
 'career': 633,
 'alone': 634,
 'reality': 635,
 'sad': 636,
 'exactly': 637,
 'huge': 638,
 'documentary': 639,
 'light': 640,
 'running': 641,
 'annoying': 642,
 'relationship': 643,
 'started': 644,
 'whose': 645,
 'wish': 646,
 'ridiculous': 647,
 'scary': 648,
 'taking': 649,
 'shots': 650,
 'husband': 651,
 'middle': 652,
 'female': 653,
 'important': 654,
 "film's": 655,
 'body': 656,
 'ends': 657,
 'turned': 658,
 'word': 659,
 'four': 660,
 'power': 661,
 'rating': 662,
 'change': 663,
 "i'll": 664,
 'major': 665,
 'opinion': 666,
 'beyond': 667,
 'call': 668,
 'level': 669,
 'somewhat': 670,
 'silly': 671,
 'country': 672,
 'talking': 673,
 'ones': 674,
 'strange': 675,
 'upon': 676,
 'room': 677,
 'usual': 678,
 'knew': 679,
 'words': 680,
 'happy': 681,
 'mostly': 682,
 'disappointed': 683,
 'apparently': 684,
 'episodes': 685,
 'novel': 686,
 'single': 687,
 'basically': 688,
 'attention': 689,
 'modern': 690,
 'problems': 691,
 'jack': 692,
 'knows': 693,
 'miss': 694,
 'finds': 695,
 'non': 696,
 'due': 697,
 'british': 698,
 'musical': 699,
 'thriller': 700,
 'class': 701,
 'cheap': 702,
 'five': 703,
 'television': 704,
 'clearly': 705,
 'talk': 706,
 'events': 707,
 "aren't": 708,
 'add': 709,
 '7': 710,
 'moving': 711,
 'fast': 712,
 'review': 713,
 'local': 714,
 'ten': 715,
 'predictable': 716,
 'sequence': 717,
 'tells': 718,
 'songs': 719,
 '8': 720,
 'team': 721,
 'dialog': 722,
 'straight': 723,
 'space': 724,
 'appears': 725,
 'whether': 726,
 'enjoyable': 727,
 'soundtrack': 728,
 'die': 729,
 'above': 730,
 'entertainment': 731,
 'earth': 732,
 'future': 733,
 'supporting': 734,
 'sets': 735,
 'easily': 736,
 'french': 737,
 'near': 738,
 'hate': 739,
 'giving': 740,
 'lots': 741,
 'within': 742,
 'tried': 743,
 'falls': 744,
 'dull': 745,
 'similar': 746,
 'sequel': 747,
 'suspense': 748,
 'release': 749,
 'filmed': 750,
 'romantic': 751,
 'mention': 752,
 'needs': 753,
 'bring': 754,
 'clear': 755,
 'subject': 756,
 "haven't": 757,
 'comic': 758,
 'working': 759,
 'eye': 760,
 'theme': 761,
 'bunch': 762,
 'george': 763,
 'message': 764,
 'surprised': 765,
 'certain': 766,
 'showing': 767,
 'easy': 768,
 "what's": 769,
 '9': 770,
 'ways': 771,
 't': 772,
 'storyline': 773,
 'stay': 774,
 'sorry': 775,
 'named': 776,
 'effort': 777,
 'sister': 778,
 'among': 779,
 'theater': 780,
 'tale': 781,
 'rock': 782,
 'stand': 783,
 'king': 784,
 'realistic': 785,
 'feature': 786,
 'using': 787,
 'editing': 788,
 'fall': 789,
 'crime': 790,
 'herself': 791,
 'minute': 792,
 'comments': 793,
 'avoid': 794,
 'deal': 795,
 'elements': 796,
 'nearly': 797,
 'typical': 798,
 'buy': 799,
 "'": 800,
 'famous': 801,
 'kept': 802,
 'greatest': 803,
 'feels': 804,
 'doubt': 805,
 'means': 806,
 'check': 807,
 'parents': 808,
 'points': 809,
 'monster': 810,
 'gone': 811,
 'dr': 812,
 'okay': 813,
 'follow': 814,
 'mystery': 815,
 'general': 816,
 'rent': 817,
 'brought': 818,
 're': 819,
 'oscar': 820,
 'actual': 821,
 'viewing': 822,
 'lady': 823,
 'richard': 824,
 'viewers': 825,
 'reviews': 826,
 'fantastic': 827,
 'imagine': 828,
 'learn': 829,
 "you've": 830,
 'material': 831,
 'move': 832,
 'period': 833,
 'form': 834,
 'begins': 835,
 'weak': 836,
 'believable': 837,
 'somehow': 838,
 'red': 839,
 'animation': 840,
 'forget': 841,
 'sequences': 842,
 'peter': 843,
 'leads': 844,
 'figure': 845,
 'fi': 846,
 'deep': 847,
 'sci': 848,
 'hear': 849,
 'particular': 850,
 'open': 851,
 'atmosphere': 852,
 'sit': 853,
 'dog': 854,
 '20': 855,
 'average': 856,
 'killing': 857,
 'surprise': 858,
 'premise': 859,
 'shame': 860,
 'paul': 861,
 'poorly': 862,
 'imdb': 863,
 'whatever': 864,
 'tom': 865,
 'lame': 866,
 'wait': 867,
 'eventually': 868,
 'acted': 869,
 'decided': 870,
 'dance': 871,
 'expected': 872,
 'indeed': 873,
 'box': 874,
 'truth': 875,
 "who's": 876,
 'note': 877,
 'season': 878,
 'doctor': 879,
 'emotional': 880,
 'forced': 881,
 'free': 882,
 'credits': 883,
 'situation': 884,
 'boys': 885,
 'crew': 886,
 'memorable': 887,
 'third': 888,
 'western': 889,
 'hot': 890,
 'romance': 891,
 'sexual': 892,
 'needed': 893,
 'york': 894,
 'difficult': 895,
 'male': 896,
 'gay': 897,
 'cheesy': 898,
 'plus': 899,
 'write': 900,
 'reading': 901,
 'unless': 902,
 'superb': 903,
 'leaves': 904,
 'nature': 905,
 'became': 906,
 'society': 907,
 'air': 908,
 'question': 909,
 'footage': 910,
 'possibly': 911,
 'begin': 912,
 'hands': 913,
 'meets': 914,
 'otherwise': 915,
 'interested': 916,
 'badly': 917,
 'forward': 918,
 'earlier': 919,
 'laughs': 920,
 'quickly': 921,
 'screenplay': 922,
 'setting': 923,
 'incredibly': 924,
 'beauty': 925,
 'effect': 926,
 'background': 927,
 'de': 928,
 'features': 929,
 'e': 930,
 'meet': 931,
 'stage': 932,
 'masterpiece': 933,
 'towards': 934,
 'inside': 935,
 'weird': 936,
 'sounds': 937,
 'comment': 938,
 'nor': 939,
 'japanese': 940,
 'whom': 941,
 'dumb': 942,
 'following': 943,
 'personal': 944,
 'street': 945,
 'copy': 946,
 'result': 947,
 'unique': 948,
 'battle': 949,
 'powerful': 950,
 'water': 951,
 'previous': 952,
 'america': 953,
 'keeps': 954,
 "let's": 955,
 'directing': 956,
 'island': 957,
 'mark': 958,
 'perfectly': 959,
 'development': 960,
 'rate': 961,
 'realize': 962,
 'lee': 963,
 'total': 964,
 'worked': 965,
 'girlfriend': 966,
 'writers': 967,
 'joke': 968,
 'fire': 969,
 'ask': 970,
 'appear': 971,
 'older': 972,
 'cop': 973,
 'business': 974,
 'mess': 975,
 'dream': 976,
 'portrayed': 977,
 'baby': 978,
 'various': 979,
 'front': 980,
 'plenty': 981,
 'creepy': 982,
 'joe': 983,
 'outside': 984,
 'present': 985,
 'spent': 986,
 'reasons': 987,
 'gun': 988,
 'brings': 989,
 'admit': 990,
 'cover': 991,
 'pay': 992,
 'dramatic': 993,
 'telling': 994,
 'bill': 995,
 'deserves': 996,
 'crazy': 997,
 'fairly': 998,
 'break': 999,
 'directors': 1000,
 ...}

In [10]:
X_train_seq = tokenizer.texts_to_sequences(X_train)
X_test_seq = tokenizer.texts_to_sequences(X_test)

In [11]:
X_train_pad = pad_sequences(X_train_seq, maxlen=MAX_LEN)
X_test_pad = pad_sequences(X_test_seq, maxlen=MAX_LEN)

In [12]:
X_train_pad

array([[ 145, 1084,   17, ...,  206,  352, 3857],
       [ 311,    6,  426, ...,   90,  104,   10],
       [   0,    0,    0, ...,    3,  711,   63],
       ...,
       [   0,    0,    0, ..., 1642,    3,  604],
       [   0,    0,    0, ...,  126, 7286,    1],
       [   0,    0,    0, ...,   71,   74, 2063]])

In [13]:
embedding_vector_features = 64 # feature representation
model = Sequential()
model.add(Embedding(VOCAB_SIZE, embedding_vector_features, input_length =MAX_LEN ))
model.add(SimpleRNN(100))
model.add(Dense(1, activation = "sigmoid"))
model.compile(loss = "binary_crossentropy", optimizer = "adam", metrics = ["accuracy"])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 embedding (Embedding)       (None, 200, 64)           640000

 simple_rnn (SimpleRNN)      (None, 100)               16500

 dense (Dense)               (None, 1)                 101

=================================================================
Total params: 656,601
Trainable params: 656,601
Non-trainable params: 0
_________________________________________________________________
None

In [14]:
X_train_seq = tokenizer.texts_to_sequences(X_train)
X_test_seq = tokenizer.texts_to_sequences(X_test)

In [15]:
X_train_seq

[[198,
  49,
  11,
  802,
  2161,
  535,
  303,
  2,
  108,
  1908,
  2039,
  4325,
  6551,
  3,
  816,
  4845,
  13,
  1,
  2,
  1,
  228,
  2,
  6191,
  80,
  783,
  54,
  53,
  23,
  102,
  5,
  2,
  28,
  2010,
  103,
  37,
  26,
  35,
  120,
  1131,
  13,
  10,
  7,
  2367,
  1191,
  6,
  455,
  49,
  553,
  6,
  93,
  34,
  24,
  40,
  917,
  401,
  1,
  16,
  2,
  167,
  6,
  2994,
  25,
  1,
  4360,
  21,
  4,
  2946,
  13,
  46,
  76,
  222,
  74,
  127,
  9,
  82,
  3156,
  196,
  21,
  240,
  3,
  2,
  448,
  8,
  8,
  11,
  206,
  4983,
  145,
  22,
  64,
  28,
  16,
  1,
  75,
  366,
  303,
  4,
  20,
  19,
  10,
  206,
  27,
  308,
  13,
  1,
  1,
  15,
  2,
  1,
  1,
  116,
  440,
  3,
  1,
  1,
  15,
  2,
  1705,
  1,
  616,
  71,
  425,
  382,
  11,
  90,
  119,
  49,
  113,
  371,
  34,
  1,
  36,
  19,
  44,
  11,
  14,
  93,
  486,
  6831,
  16,
  4,
  365,
  1,
  1183,
  1,
  62,
  1,
  1,
  9,
  2,
  471,
  217,
  1015,
  6,
  4161,
  9,
  4,
  175,
  5,
  35,
  441,
  698,
  624,
  13,
  3749,
  238,
  112,
  849,
  36,
  171,
  31,
  220,
  198,
  2,
  429,
  368,
  56,
  3766,
  4,
  279,
  1,
  8,
  8,
  158,
  1708,
  188,
  7,
  2,
  1,
  1,
  728,
  1936,
  2,
  1201,
  5,
  2947,
  1,
  3750,
  1829,
  3,
  1,
  148,
  145,
  4,
  229,
  5,
  4,
  208,
  324,
  3,
  145,
  1084,
  17,
  89,
  5,
  133,
  2872,
  8744,
  19,
  11,
  154,
  9254,
  100,
  5,
  2,
  4021,
  303,
  12,
  18,
  1002,
  36,
  2,
  1,
  497,
  493,
  2620,
  250,
  72,
  78,
  108,
  108,
  699,
  1,
  61,
  1,
  87,
  1048,
  1364,
  6,
  230,
  133,
  24,
  4361,
  32,
  139,
  1,
  210,
  1155,
  15,
  4502,
  5314,
  32,
  4,
  1,
  2387,
  3,
  1,
  9,
  1,
  12,
  7,
  4,
  446,
  15,
  625,
  5,
  2,
  719,
  2960,
  2,
  1279,
  1,
  3,
  72,
  3617,
  2,
  167,
  1508,
  2,
  1246,
  6,
  1630,
  2,
  880,
  1269,
  6,
  2,
  311,
  141,
  2895,
  3,
  411,
  634,
  8,
  8,
  2,
  270,
  7,
  3554,
  1001,
  6,
  27,
  40,
  1,
  15,
  1382,
  218,
  66,
  1,
  3,
  47,
  7,
  31,
  220,
  28,
  194,
  1485,
  9,
  1102,
  19,
  11,
  4906,
  1,
  1,
  85,
  2,
  227,
  67,
  357,
  69,
  55,
  28,
  6,
  3601,
  16,
  45,
  22,
  193,
  6,
  8256,
  4,
  890,
  3512,
  1759,
  23,
  26,
  6,
  159,
  197,
  176,
  4,
  111,
  13,
  1653,
  472,
  76,
  222,
  6,
  326,
  3,
  3513,
  37,
  24,
  51,
  73,
  1890,
  4730,
  15,
  10,
  1394,
  12,
  20,
  7,
  4,
  3555,
  2030,
  17,
  62,
  2,
  2437,
  471,
  533,
  3,
  4,
  172,
  2578,
  1,
  2762,
  1779,
  6,
  586,
  10,
  36,
  2,
  3798,
  451,
  156,
  206,
  352,
  3857],
 [11,
  117,
  22,
  104,
  2,
  439,
  18,
  11,
  98,
  22,
  104,
  2,
  439,
  18,
  11,
  2305,
  2,
  267,
  101,
  147,
  16,
  306,
  33,
  528,
  3,
  11,
  1460,
  250,
  539,
  5,
  147,
  521,
  10,
  544,
  521,
  160,
  649,
  2,
  3674,
  42,
  5,
  2,
  414,
  8,
  8,
  11,
  38,
  4005,
  97,
  196,
  1652,
  3,
  758,
  19,
  1,
  1,
  68,
  62,
  27,
  2114,
  15,
  4,
  1652,
  596,
  31,
  4,
  4005,
  209,
  8,
  8,
  2,
  446,
  7,
  1,
  1,
  335,
  509,
  99,
  248,
  6,
  78,
  2,
  311,
  6,
  426,
  2,
  111,
  185,
  6,
  27,
  33,
  1386,
  16,
  711,
  1342,
  1,
  1,
  36,
  28,
  129,
  6,
  158,
  1,
  312,
  7,
  338,
  1,
  3,
  1508,
  4118,
  39,
  1,
  30,
  25,
  675,
  6552,
  214,
  622,
  15,
  2091,
  1342,
  1,
  7,
  705,
  1,
  252,
  73,
  649,
  4,
  217,
  10,
  1,
  23,
  204,
  42,
  5,
  2,
  63,
  254,
  129,
  7,
  1309,
  716,
  2,
  1,
  1,
  13,
  81,
  3751,
  21,
  2,
  269,
  7,
  583,
  15,
  529,
  15,
  254,
  129,
  7,
  1722,
  9,
  1373,
  139,
  15,
  447,
  4878,
  2,
  9147,
  2124,
  32,
  2,
  418,
  109,
  24,
  155,
  85,
  23,
  68,
  1,
  17,
  2,
  103,
  4702,
  3,
  2561,
  1607,
  3,
  2,
  884,
  2,
  109,
  657,
  54,
  9,
  7,
  22,
  1,
  1,
  189,
  410,
  2,
  561,
  13,
  29,
  7,
  4388,
  1,
  54,
  9,
  4,
  1861,
  596,
  6,
  2452,
  4,
  426,
  36,
  2,
  311,
  8,
  8,
  44,
  1342,
  67,
  22,
  255,
  139,
  33,
  1132,
  109,
  37,
  112,
  64,
  1,
  17,
  2,
  82,
  103,
  9,
  2,
  18,
  3,
  645,
  4846,
  7,
  1108,
  6832,
  554,
  16,
  265,
  6,
  2452,
  920,
  3,
  2,
  209,
  135,
  1208,
  35,
  716,
  3,
  7253,
  30,
  2,
  619,
  462,
  226,
  99,
  1084,
  12,
  18,
  98,
  26,
  76,
  1723,
  19,
  10,
  216,
  90,
  104,
  10],
 [4,
  1336,
  114,
  63,
  2837,
  5,
  1,
  2,
  1279,
  16,
  1,
  4571,
  2595,
  21,
  1717,
  3951,
  3,
  87,
  12,
  7,
  331,
  32,
  4222,
  84,
  6,
  5722,
  1355,
  6,
  254,
  82,
  2,
  63,
  2745,
  21,
  4,
  1,
  37,
  490,
  35,
  74,
  6,
  27,
  4,
  2240,
  1659,
  15,
  70,
  15,
  4,
  50,
  651,
  3,
  354,
  4,
  6833,
  1407,
  7,
  52,
  3526,
  6,
  88,
  15,
  2,
  63,
  4223,
  72,
  65,
  2,
  1337,
  1775,
  2,
  2317,
  9,
  25,
  855,
  301,
  1516,
  3,
  87,
  29,
  1,
  17,
  2,
  1530,
  1,
  13,
  396,
  88,
  4,
  316,
  3,
  711,
  63],
 [12,
  1614,
  256,
  3469,
  1,
  7,
  4,
  452,
  4431,
  1,
  1906,
  17,
  33,
  1,
  1,
  7829,
  1,
  37,
  1093,
  1,
  397,
  6,
  992,
  124,
  25,
  123,
  4306,
  1,
  32,
  1,
  48,
  5,
  2,
  1,
  1,
  23,
  81,
  123,
  4181,
  126,
  514,
  21,
  3,
  37,
  40,
  572,
  6,
  27,
  2896,
  1,
  2,
  3469,
  8640,
  227,
  80,
  1,
  6,
  1,
  4,
  172,
  1,
  1709,
  796,
  61,
  62,
  947,
  9,
  48,
  2014,
  974,
  1189,
  4,
  3448,
  61,
  515,
  774,
  271,
  33,
  1365,
  1811,
  1439,
  37,
  515,
  544,
  1166,
  505,
  22,
  6,
  752,
  4,
  1,
  761,
  723,
  42,
  5,
  2,
  1407,
  5,
  1,
  257,
  9,
  12,
  414,
  2,
  107,
  1,
  5722,
  2698,
  1782,
  3858,
  1490,
  3556,
  9,
  2,
  128,
  11,
  195,
  132,
  145,
  765,
  13,
  12,
  20,
  275,
  55,
  2023,
  5,
  2,
  8641,
  5,
  3735,
  1,
  1,
  16,
  2,
  1,
  5123,
  61,
  10,
  3767,
  9,
  435,
  771,
  3,
  13,
  10,
  7,
  1458,
  6,
  1601,
  2596,
  54,
  2,
  1,
  2081,
  19,
  625,
  99,
  1094,
  282,
  5,
  1,
  9503,
  3,
  1,
  39,
  5603,
  1454,
  17,
  61,
  3035,
  3469,
  67,
  32,
  92,
  434,
  338,
  3470],
 [86,
  5,
  30,
  11,
  5451,
  261,
  13,
  7989,
  97,
  24,
  5452,
  391,
  127,
  36,
  2,
  2300,
  880,
  105,
  5,
  2,
  1693,
  3,
  1229,
  97,
  36,
  12,
  276,
  159,
  644,
  6,
  2988,
  4,
  229,
  5,
  1197,
  828,
  821,
  1373,
  71,
  91,
  97,
  71,
  159,
  1840,
  6,
  78,
  431,
  3,
  155,
  15,
  3449,
  6,
  191,
  459,
  2287,
  3,
  345,
  8,
  8,
  303,
  2,
  3214,
  3,
  1,
  435,
  64,
  79,
  97,
  71,
  91,
  32,
  4,
  1,
  1,
  5,
  1066,
  18,
  101,
  18,
  71,
  6553,
  32,
  1427,
  3,
  255,
  4136,
  5,
  288,
  10,
  906,
  2,
  5973,
  8,
  8,
  92,
  384,
  2250,
  8,
  8,
  1383,
  1040,
  45,
  40,
  335,
  22,
  155,
  22,
  283,
  22,
  123,
  19,
  2,
  149,
  7,
  72,
  102,
  95,
  155,
  85,
  1048,
  331,
  6,
  7989,
  97,
  6,
  27,
  155,
  264,
  17,
  4,
  175,
  38,
  12,
  17,
  4,
  172,
  64,
  155,
  4984,
  19,
  34,
  1130,
  132,
  939,
  77,
  233,
  155,
  5286,
  2,
  464,
  121,
  69,
  2,
  464,
  7,
  10,
  2,
  2050,
  7069,
  255,
  32,
  1,
  1,
  7,
  10,
  2,
  4703,
  452,
  3752,
  2108,
  2040,
  3052,
  7,
  10,
  2,
  9746,
  32,
  1,
  1,
  2,
  18,
  7,
  40,
  22,
  155,
  8,
  8,
  19,
  1580,
  22,
  57,
  280,
  8642,
  43,
  2250,
  13,
  4098,
  7,
  2,
  9747,
  3,
  10,
  7,
  134,
  11,
  1100,
  13,
  7989,
  1373,
  26,
  214,
  6,
  4,
  1,
  234,
  11,
  26,
  106,
  12,
  9,
  108,
  82,
  97,
  15,
  70,
  30,
  2,
  56,
  23,
  40,
  119,
  95,
  165,
  6,
  128,
  70,
  30,
  103,
  24,
  637,
  15,
  34,
  24,
  1369,
  9,
  2,
  378,
  5,
  2,
  18,
  3,
  1382,
  218,
  637,
  49,
  34,
  1760,
  9,
  2,
  128,
  224,
  425,
  55,
  677,
  16,
  2517,
  31,
  30,
  8,
  8,
  30,
  9,
  30,
  11,
  68,
  132,
  13,
  11,
  1800,
  17,
  4,
  75,
  561,
  101,
  315,
  12,
  18,
  10,
  14,
  2,
  28,
  18,
  13,
  91,
  69,
  962,
  13,
  72,
  238,
  360,
  48,
  170,
  557,
  9,
  7989,
  18,
  232,
  171,
  8,
  8,
  662,
  304,
  1045],
 [11,
  90,
  119,
  87,
  12,
  18,
  1973,
  35,
  108,
  1153,
  826,
  21,
  12,
  2061,
  145,
  4,
  194,
  1,
  324,
  3,
  236,
  52,
  1084,
  17,
  2,
  63,
  12,
  6291,
  210,
  20,
  1,
  667,
  2615,
  19,
  58,
  44,
  11,
  292,
  2,
  334,
  113,
  52,
  334,
  1055,
  1898,
  1,
  15,
  2,
  512,
  8446,
  3,
  30,
  184,
  2137,
  5315,
  2,
  4287,
  338,
  3911,
  3,
  1378,
  1248,
  487,
  5484,
  12,
  4408,
  1180,
  1723,
  296,
  3386,
  42,
  87,
  1033,
  13,
  1,
  1,
  350,
  14,
  44,
  23,
  340,
  13,
  3,
  188,
  13,
  14,
  1060,
  758,
  3584,
  1056,
  10,
  238,
  14,
  2,
  89,
  5014,
  155,
  174,
  5,
  2,
  18,
  273,
  467,
  38,
  12,
  18,
  19,
  44,
  339,
  4,
  1,
  324,
  39,
  22,
  338,
  2062,
  90,
  65,
  10,
  591],
 [1958,
  2562,
  400,
  4,
  175,
  5,
  647,
  152,
  17,
  58,
  346,
  5,
  33,
  323,
  5,
  49,
  7,
  165,
  21,
  73,
  2,
  167,
  67,
  44,
  23,
  68,
  828,
  13,
  47,
  7,
  55,
  1,
  111,
  39,
  63,
  2,
  299,
  282,
  24,
  4,
  968,
  3,
  58,
  2,
  438,
  7,
  382,
  12,
  20,
  14,
  516,
  32,
  1655,
  1,
  10,
  14,
  2,
  62,
  20,
  13,
  29,
  123,
  516,
  3,
  2,
  287,
  7,
  583],
 [1296,
  4731,
  8,
  8,
  1,
  1,
  64,
  4,
  50,
  225,
  19,
  101,
  33,
  3348,
  17,
  48,
  1026,
  9,
  4,
  4119,
  3,
  48,
  1,
  5,
  3966,
  241,
  1395,
  6,
  2587,
  39,
  252,
  48,
  427,
  5,
  161,
  1226,
  29,
  2995,
  19,
  101,
  4,
  330,
  137,
  241,
  1019,
  283,
  171,
  12,
  56,
  657,
  54,
  9,
  4,
  1,
  635,
  121,
  9,
  61,
  241,
  442,
  6,
  497,
  16,
  4,
  137,
  36,
  4,
  762,
  5,
  1262,
  449,
  17,
  279,
  1432,
  3,
  868,
  729,
  19,
  72,
  30,
  119,
  8745,
  3,
  72,
  30,
  119,
  13,
  241,
  1,
  73,
  58,
  2,
  1,
  5,
  1262,
  449,
  8,
  8,
  11,
  64,
  461,
  6,
  38,
  12,
  18,
  110,
  33,
  8745,
  324,
  3,
  30,
  189,
  2,
  641,
  130,
  1379,
  99,
  108,
  1513,
  13,
  64,
  8746,
  2,
  584,
  42,
  5,
  69,
  930,
  1334,
  2,
  1,
  5,
  1,
  558,
  935,
  2,
  4119,
  118,
  2,
  2256,
  311,
  7,
  1203,
  4,
  330,
  2621,
  5,
  2,
  3348,
  594,
  17,
  436,
  156,
  279,
  358,
  2438,
  12,
  806,
  13,
  2,
  1270,
  4119,
  9,
  61,
  8745,
  8447,
  14,
  1,
  17,
  215,
  156,
  3967,
  1401,
  2,
  886,
  1035,
  28,
  5,
  61,
  935,
  2,
  760,
  5,
  28,
  5,
  2,
  886,
  1035,
  8745,
  3720,
  8,
  8,
  47,
  24,
  82,
  1513,
  80,
  3,
  2,
  111,
  61,
  9,
  2687,
  185,
  6,
  27,
  52,
  223,
  3,
  4162,
  506,
  16,
  4,
  137,
  92,
  10,
  427,
  5,
  2226,
  4,
  3150,
  5,
  1,
  3,
  1,
  9,
  61,
  10,
  1,
  8,
  8,
  2,
  113,
  195,
  64,
  27,
  308,
  6,
  27,
  233,
  127,
  73,
  1378,
  2280,
  17,
  8745,
  9,
  2,
  1013,
  217,
  408,
  33,
  856,
  8745,
  242,
  2,
  367,
  5,
  2,
  175,
  78,
  32,
  205,
  110,
  264,
  50,
  39,
  75,
  8,
  8,
  2,
  299,
  282,
  24,
  574,
  205,
  110,
  1165,
  8,
  8,
  662,
  336,
  156],
 [2,
  84,
  37,
  24,
  75,
  1,
  12,
  20,
  24,
  146,
  37,
  90,
  387,
  20,
  6,
  912,
  17,
  133,
  24,
  2,
  84,
  37,
  114,
  18,
  8083,
  3,
  1,
  6,
  100,
  18,
  13,
  150,
  328,
  1,
  1,
  6774,
  1,
  7,
  4,
  3450,
  120,
  20,
  13,
  200,
  313,
  2708,
  3,
  273,
  58,
  369,
  31,
  86,
  19,
  49,
  10,
  1508,
  9,
  111,
  10,
  51,
  73,
  162,
  54,
  16,
  9,
  2368,
  8,
  8,
  28,
  149,
  9,
  850,
  43,
  2,
  18,
  13,
  1522,
  69,
  14,
  45,
  363,
  5,
  208,
  61,
  309,
  4,
  1029,
  174,
  146,
  1473,
  5,
  20,
  208,
  81,
  1384,
  87,
  654,
  208,
  7,
  9,
  2,
  18,
  196,
  9,
  1,
  3,
  1,
  115,
  3,
  9,
  2,
  927,
  1,
  761,
  1,
  761,
  3,
  1,
  761,
  24,
  30,
  546,
  9,
  2,
  613,
  717,
  3,
  10,
  7,
  155,
  87,
  48,
  5,
  2,
  3968,
  294,
  42,
  16,
  2006,
  9,
  2,
  129,
  118,
  2,
  347,
  24,
  1166,
  3929,
  5,
  5184,
  1,
  7,
  17,
  6774,
  53,
  2,
  347,
  1986,
  138,
  38,
  59,
  7,
  57,
  251,
  3,
  92,
  59,
  272,
  122,
  6,
  3836,
  6,
  197,
  88,
  138,
  53,
  2,
  347,
  1986,
  2,
  1,
  59,
  81,
  27,
  57,
  251,
  4631,
  767,
  2,
  1123,
  207,
  2,
  107,
  1159,
  47,
  24,
  30,
  2537,
  5,
  120,
  1,
  38,
  12,
  935,
  2,
  18,
  3,
  137,
  10,
  200,
  164,
  38,
  4,
  4326,
  21,
  2,
  984,
  2,
  144,
  1407,
  5,
  20,
  81,
  1384,
  87,
  50,
  12,
  18,
  64,
  7],
 [8,
  8,
  15,
  678,
  11,
  14,
  64,
  258,
  918,
  6,
  4,
  170,
  240,
  20,
  21,
  4,
  1681,
  756,
  5,
  1749,
  162,
  4,
  332,
  663,
  36,
  4,
  2822,
  1084,
  639,
  43,
  1,
  39,
  8946,
  21,
  2,
  484,
  1215,
  8,
  8,
  11,
  1,
  588,
  918,
  6,
  4137,
  1,
  3,
  2218,
  31,
  2,
  6368,
  19,
  14,
  1,
  818,
  178,
  6,
  732,
  17,
  2,
  1,
  5,
  2,
  1,
  369,
  1,
  661,
  5,
  373,
  3,
  95,
  1246,
  6,
  1144,
  33,
  1573,
  3557,
  21,
  4408,
  8,
  8,
  35,
  246,
  171,
  11,
  187,
  2241,
  43,
  1046,
  2291,
  5,
  1,
  264,
  15,
  11,
  546,
  13,
  3750,
  1,
  14,
  575,
  15,
  199,
  502,
  25,
  1230,
  11,
  68,
  65,
  136,
  29,
  4732,
  8,
  8,
  6,
  3116,
  48,
  225,
  1820,
  16,
  12,
  1921,
  8,
  8,
  2,
  1,
  278,
  14,
  33,
  8747,
  417,
  29,
  308,
  10,
  14,
  8,
  8,
  179,
  2371,
  72,
  893,
  51,
  6055,
  8,
  8,
  6055,
  24,
  34,
  452,
  4951,
  7387,
  115,
  577,
  27,
  308,
  6,
  27,
  205,
  1,
  432,
  1,
  107,
  5674,
  2404,
  1,
  71,
  191,
  3,
  3675,
  19,
  34,
  71,
  442,
  6,
  27,
  8,
  8,
  2,
  1,
  508,
  1,
  5,
  1,
  185,
  6,
  27,
  8,
  8,
  2404,
  14,
  4,
  52,
  75,
  130,
  55,
  29,
  14,
  4,
  52,
  75,
  130,
  37,
  1785,
  4503,
  3,
  40,
  9,
  414,
  23,
  694,
  12,
  1048,
  165,
  6,
  1,
  2,
  192,
  9,
  173,
  129,
  9,
  2,
  20,
  8,
  8,
  47,
  14,
  55,
  777,
  1618,
  6,
  352,
  3,
  1237,
  2,
  1279,
  5,
  2,
  56,
  3,
  136,
  2404,
  200,
  26,
  5566,
  2,
  2910,
  3,
  1,
  29,
  117,
  3188,
  6,
  132,
  1038,
  2,
  1300,
  317,
  1,
  4,
  1742,
  36,
  1,
  12,
  20,
  7452,
  6,
  219,
  42,
  2,
  192,
  13,
  797,
  30,
  5,
  2,
  6554,
  5,
  2,
  1,
  4362,
  4306,
  71,
  2466,
  3,
  13,
  12,
  200,
  26,
  1,
  25,
  2910,
  21,
  2,
  756,
  3,
  25,
  1,
  1,
  5,
  2,
  4503,
  17,
  1,
  33,
  425,
  4288,
  1255,
  6,
  1757,
  74,
  5,
  2,
  2989,
  1022,
  8,
  8,
  19,
  47,
  14,
  22,
  74,
  1757,
  6,
  27,
  222,
  2,
  20,
  1198,
  1208,
  165,
  6,
  140,
  47,
  35,
  72,
  40,
  187,
  30,
  2,
  530,
  72,
  679,
  43,
  547,
  72,
  421,
  90,
  78,
  2,
  1456,
  192,
  13,
  1,
  1,
  6,
  61,
  46,
  2404,
  3374,
  110,
  4,
  1,
  4362,
  1204,
  101,
  1,
  13,
  60,
  5,
  266,
  27,
  226,
  99,
  1308,
  16,
  2,
  20,
  6,
  2794,
  3,
  237,
  58,
  6716,
  36,
  2,
  6555,
  1,
  14,
  52,
  1,
  1,
  61,
  1,
  243,
  1,
  8,
  8,
  72,
  119,
  29,
  14,
  4,
  75,
  130,
  189,
  72,
  80,
  119,
  13,
  29,
  14,
  4,
  1,
  845,
  196,
  15,
  4,
  1070,
  1,
  3,
  9,
  51,
  2066,
  1133,
  29,
  98,
  27,
  9504,
  3,
  58,
  2138,
  3,
  5,
  266,
  1,
  48,
  2910,
  38,
  1,
  1101,
  4794,
  3,
  1101,
  3234,
  13,
  108,
  8084,
  5974,
  98,
  1008,
  17,
  29,
  14,
  80,
  1,
  4045,
  5,
  1562,
  3022,
  136,
  13,
  5520,
  5351,
  854,
  1,
  129,
  14,
  35,
  1771,
  8,
  8,
  29,
  14,
  80,
  36,
  30,
  2,
  5975,
  199,
  106,
  4,
  2785,
  1688,
  9,
  1,
  1837,
  72,
  213,
  88,
  17,
  25,
  4058,
  1623,
  72,
  112,
  78,
  6,
  65,
  87,
  29,
  1273,
  10,
  1402,
  5,
  9379,
  71,
  22,
  9,
  2,
  227,
  3188,
  6,
  132,
  72,
  80,
  78,
  55,
  2622,
  1618,
  83,
  136,
  29,
  14,
  35,
  3898,
  54,
  32,
  25,
  297,
  2490,
  1837,
  1,
  4099,
  1,
  1,
  3,
  35,
  108,
  406,
  253,
  10,
  35,
  1,
  33,
  563,
  3,
  171,
  38,
  2,
  219,
  730,
  819,
  2,
  2466,
  1,
  4307,
  12,
  7,
  5382,
  6,
  5927,
  1757,
  43,
  2,
  756,
  136,
  117,
  29,
  114,
  297,
  35,
  74,
  136,
  117,
  29,
  102,
  10,
  14,
  212,
  4,
  50,
  323,
  473,
  2550,
  2067,
  6,
  2,
  3859,
  136,
  154,
  29,
  455,
  43,
  25,
  6717,
  37,
  1079,
  39,
  273,
  29,
  117,
  19,
  131,
  2746,
  2,
  361,
  7990,
  8,
  8,
  12,
  20,
  421,
  154,
  26,
  233,
  5,
  100,
  611,
  6,
  132,
  21,
  12,
  343,
  8,
  8,
  15,
  30,
  99,
  409,
  133,
  482,
  2,
  20,
  7,
  4,
  364,
  475,
  5,
  1,
  484,
  3349,
  6,
  2,
  1,
  3,
  1,
  530,
  39,
  1173,
  2050,
  2180,
  42,
  6,
  1119,
  9,
  17,
  1046,
  1,
  61,
  30,
  99,
  409,
  7,
  6,
  1,
  6,
  2,
  4592,
  1116,
  1,
  118,
  23,
  90,
  1733,
  126,
  311,
  33,
  7388,
  35,
  23,
  40,
  8171,
  530,
  178,
  66,
  8643,
  1340,
  1056,
  4847,
  13,
  467,
  212,
  78,
  243,
  17,
  10,
  85,
  47,
  24,
  35,
  108,
  942,
  6056,
  9,
  2,
  180,
  8,
  8,
  484,
  7,
  64,
  43,
  232,
  176,
  3349,
  6,
  2,
  510,
  3,
  315,
  87,
  10,
  6493,
  260,
  985,
  16,
  127,
  3,
  16,
  430,
  12,
  1921,
  14,
  4,
  79,
  1447,
  433,
  171,
  34,
  986,
  3140,
  21,
  10,
  3,
  2,
  1739,
  3,
  1029,
  135,
  71,
  1165,
  19,
  560,
  176,
  163,
  31,
  30,
  72,
  154,
  119,
  472,
  3,
  6326,
  55,
  1757,
  5,
  12,
  459,
  833,
  9,
  394,
  484,
  8,
  8,
  1],
 [11,
  502,
  2,
  230,
  5,
  2,
  613,
  172,
  228,
  19,
  855,
  228,
  9,
  11,
  14,
  1,
  1,
  2,
  712,
  918,
  3512,
  226,
  99,
  108,
  650,
  5,
  1574,
  501,
  1,
  1310,
  36,
  677,
  6,
  677,
  178,
  1,
  141,
  3471,
  3,
  178,
  2,
  945,
  3,
  15,
  108,
  650,
  5,
  88,
  258,
  1,
  3,
  1461,
  511,
  69,
  2,
  1370,
  13,
  2,
  63,
  67,
  1867,
  76,
  1001,
  15,
  4,
  330,
  855,
  1077,
  228,
  3,
  92,
  5675,
  83,
  4,
  786,
  15,
  4,
  1,
  5,
  114,
  207,
  167,
  1,
  3,
  328,
  1,
  34,
  1043,
  1058,
  2,
  922,
  8,
  8,
  10,
  237,
  26,
  76,
  51,
  431,
  44,
  100,
  5,
  2,
  103,
  67,
  233,
  6,
  132,
  13,
  11,
  1956,
  546,
  308,
  9,
  108,
  82,
  105,
  160,
  39,
  44,
  2,
  270,
  292,
  1,
  2,
  28,
  11,
  67,
  9148,
  281,
  228,
  83,
  2,
  20,
  1,
  16,
  33,
  1734,
  4100,
  1193,
  20,
  31,
  220,
  95,
  488,
  14,
  9,
  2,
  204,
  276,
  10,
  292,
  126,
  1248,
  4459,
  373,
  5124,
  1862],
 [12,
  18,
  14,
  35,
  75,
  3,
  35,
  702,
  3,
  35,
  2041,
  11,
  253,
  12,
  18,
  6,
  27,
  28,
  5,
  2,
  89,
  345,
  562,
  1786,
  399,
  1229,
  97,
  13,
  11,
  26,
  123,
  106,
  11,
  38,
  89,
  1229,
  702,
  183,
  97,
  19,
  11,
  60,
  112,
  817,
  12,
  28,
  171,
  10,
  40,
  117,
  22,
  94,
  100,
  284,
  4,
  235,
  13,
  468,
  9,
  2,
  1592,
  5453,
  66,
  495,
  25,
  327,
  3,
  66,
  559,
  6,
  1144,
  56,
  17,
  93,
  16,
  2,
  1,
  3,
  303,
  2,
  18,
  16,
  48,
  287,
  2,
  413,
  3,
  559,
  9,
  1141,
  77,
  22,
  78,
  342,
  70,
  72,
  112,
  845,
  42,
  136,
  359,
  215,
  2379,
  2,
  128,
  5,
  2,
  18,
  19,
  359,
  92,
  30,
  72,
  65,
  7,
  2,
  192,
  13,
  2,
  413,
  46,
  48,
  834,
  5,
  1,
  3,
  2,
  559,
  9,
  1141,
  7,
  263,
  4209,
  3,
  2092,
  5,
  4,
  9748,
  5,
  49,
  81,
  572,
  6,
  2408,
  1539,
  6,
  12,
  149,
  13,
  72,
  26,
  55,
  2251,
  15,
  6,
  49,
  10,
  286,
  38,
  30,
  72,
  65,
  7,
  4,
  1922,
  640,
  1,
  25,
  1514,
  3,
  30,
  72,
  849,
  7,
  4,
  702,
  2823,
  5,
  9900,
  1,
  2219,
  3,
  4,
  728,
  2699,
  36,
  979,
  183,
  97,
  92,
  53,
  72,
  415,
  166,
  42,
  49,
  3,
  37,
  10,
  7,
  30,
  11,
  117,
  14,
  426,
  12,
  494,
  519,
  42,
  6,
  27,
  48,
  244,
  5,
  1132,
  940,
  3969,
  36,
  8331,
  37,
  46,
  684,
  214,
  142,
  6,
  115,
  6,
  2433,
  2,
  413,
  3,
  41,
  235,
  3,
  30,
  2,
  413,
  125,
  7,
  783,
  47,
  9,
  980,
  5,
  2,
  585,
  677,
  5723,
  17,
  41,
  913,
  21,
  969,
  39,
  138,
  38,
  470,

In [16]:
X_train_pad = pad_sequences(X_train_seq, maxlen=MAX_LEN)
X_test_pad = pad_sequences(X_test_seq, maxlen=MAX_LEN)

In [17]:
X_train_pad

array([[ 145, 1084,   17, ...,  206,  352, 3857],
       [ 311,    6,  426, ...,   90,  104,   10],
       [   0,    0,    0, ...,    3,  711,   63],
       ...,
       [   0,    0,    0, ..., 1642,    3,  604],
       [   0,    0,    0, ...,  126, 7286,    1],
       [   0,    0,    0, ...,   71,   74, 2063]])

In [18]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense

VOCAB_SIZE = 10000
EMBEDDING_DIM = 100
MAX_LEN = 200   # sequence length

model = Sequential([
    Embedding(input_dim=VOCAB_SIZE,
              output_dim=EMBEDDING_DIM,
              input_shape=(MAX_LEN,)),
    SimpleRNN(64),
    Dense(1, activation='sigmoid')
])

model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 embedding_1 (Embedding)     (None, 200, 100)          1000000

 simple_rnn_1 (SimpleRNN)    (None, 64)                10560

 dense_1 (Dense)             (None, 1)                 65

=================================================================
Total params: 1,010,625
Trainable params: 1,010,625
Non-trainable params: 0
_________________________________________________________________

In [19]:
model.compile(loss = "binary_crossentropy", optimizer = "adam", metrics = ["accuracy"])
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 embedding_1 (Embedding)     (None, 200, 100)          1000000

 simple_rnn_1 (SimpleRNN)    (None, 64)                10560

 dense_1 (Dense)             (None, 1)                 65

=================================================================
Total params: 1,010,625
Trainable params: 1,010,625
Non-trainable params: 0
_________________________________________________________________
None

In [ ]:
# model training
model.fit(X_train_pad, y_train, validation_data = (X_test_pad, y_test), epochs = 10, batch_size = 64)

Epoch 1/10
625/625 [==============================] - 76s 122ms/step - loss: 0.5372 - accuracy: 0.7210 - val_loss: 0.4883 - val_accuracy: 0.7684
Epoch 2/10
625/625 [==============================] - 79s 126ms/step - loss: 0.4149 - accuracy: 0.8120 - val_loss: 0.5715 - val_accuracy: 0.6938
Epoch 3/10
625/625 [==============================] - 73s 117ms/step - loss: 0.4444 - accuracy: 0.8037 - val_loss: 0.4909 - val_accuracy: 0.7693
Epoch 4/10
625/625 [==============================] - 72s 115ms/step - loss: 0.4007 - accuracy: 0.8306 - val_loss: 0.5934 - val_accuracy: 0.6744
Epoch 5/10
625/625 [==============================] - 75s 120ms/step - loss: 0.3364 - accuracy: 0.8626 - val_loss: 0.4632 - val_accuracy: 0.7891
Epoch 6/10
625/625 [==============================] - 79s 127ms/step - loss: 0.3768 - accuracy: 0.8357 - val_loss: 0.5686 - val_accuracy: 0.7067
Epoch 7/10
625/625 [==============================] - 78s 125ms/step - loss: 0.3600 - accuracy: 0.8521 - val_loss: 0.4409 - val_accuracy: 0.8175
Epoch 8/10
625/625 [==============================] - 77s 123ms/step - loss: 0.4146 - accuracy: 0.8188 - val_loss: 0.5257 - val_accuracy: 0.7358
Epoch 9/10
625/625 [==============================] - 83s 133ms/step - loss: 0.3109 - accuracy: 0.8751 - val_loss: 0.4599 - val_accuracy: 0.8191
Epoch 10/10
625/625 [==============================] - 77s 124ms/step - loss: 0.3155 - accuracy: 0.8755 - val_loss: 0.5026 - val_accuracy: 0.7663

:

In [22]:
y_pred = model.predict(X_test_pad)

313/313 [==============================] - 2s 7ms/step

In [23]:
y_pred = np.where(y_pred>0.4, 1,0)
y_pred

array([[1],
       [1],
       [1],
       ...,
       [0],
       [0],
       [1]])

In [24]:
y_test

array([1, 1, 0, ..., 1, 0, 1], dtype=int64)

In [25]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [26]:
pd.DataFrame(confusion_matrix(y_test, y_pred))

      0     1
0  4044   917
1   951  4088

In [27]:
accuracy_score(y_test, y_pred)

0.8132

In [28]:
import pickle

model.save("sentiment_model.h5")

with open("tokenizer.pkl", "wb") as f:
    pickle.dump(tokenizer, f)

In [29]:
%%writefile app.py
import streamlit as st
import numpy as np
import pickle
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.sequence import pad_sequences

# -------------------------------
# Load model and tokenizer
# -------------------------------
model = load_model("sentiment_model.h5")

with open("tokenizer.pkl", "rb") as f:
    tokenizer = pickle.load(f)

MAX_LEN = 200   # same as training

# -------------------------------
# Streamlit UI
# -------------------------------
st.set_page_config(page_title="Sentiment Analysis App", layout="centered")

st.title("🧠 Sentiment Analysis Web App")
st.write("Binary Classification (Positive / Negative)")
st.write("Model Accuracy: **64%**")

# Text input
user_text = st.text_area("Enter your review or sentence:", height=150)

# Prediction button
if st.button("Predict Sentiment"):

    if len(user_text.strip()) == 0:
        st.warning("Please enter some text.")
    else:
        # Tokenization
        seq = tokenizer.texts_to_sequences([user_text])
        padded = pad_sequences(seq, maxlen=MAX_LEN, padding="post")

        # Prediction
        pred = model.predict(padded)[0][0]

        # Decision threshold
        sentiment = "Positive 😊" if pred > 0.5 else "Negative 😞"

        # Display result
        st.subheader("Prediction Result")
        st.write("Sentiment:", sentiment)
        st.write("Confidence Score:", round(float(pred), 3))

Writing app.py

In [31]:
from pyngrok import ngrok

In [32]:
!streamlit run app.py &>/content/logs.txt &

OSError: Background processes not supported.

In [ ]:
# Replace 'YOUR_AUTHTOKEN_HERE' with your actual token from https://dashboard.ngrok.com/get-started/your-authtoken
import os
from pyngrok import ngrok

AUTHTOKEN = "YOUR_AUTHTOKEN_HERE"
ngrok.set_auth_token(AUTHTOKEN)

public_url = ngrok.connect(8501)
public_url